-- Expand QuizVerse categories and question banks.
-- Run after 001_create_quizverse_schema.sql, 002_seed_categories_questions.sql,
-- and 003_upgrade_quizverse_platform.sql on existing projects.

INSERT INTO public.categories (name, slug, description, icon, color) VALUES
  ('Geography', 'geography', 'Explore countries, capitals, maps, landmarks, and Earth extremes.', 'globe', '#3B82F6'),
  ('Music', 'music', 'Test artists, instruments, genres, theory, and iconic records.', 'music', '#8B5CF6'),
  ('Health', 'health', 'Learn human body facts, wellness basics, nutrition, and medicine.', 'heart', '#EF4444'),
  ('Science', 'science', 'Explore physics, chemistry, biology, space, and natural forces.', 'atom', '#10B981'),
  ('History', 'history', 'Travel through empires, inventions, revolutions, and world events.', 'landmark', '#F59E0B'),
  ('Coding', 'coding', 'Practice programming concepts, web basics, data structures, and debugging.', 'code', '#06B6D4'),
  ('Technology', 'technology', 'Challenge yourself on computers, internet culture, AI, hardware, and security.', 'cpu', '#6366F1'),
  ('Sports', 'sports', 'Answer questions about global games, records, rules, and legendary athletes.', 'trophy', '#22C55E'),
  ('Movies', 'movies', 'Recognize films, directors, genres, awards, and big-screen moments.', 'film', '#EC4899'),
  ('Literature', 'literature', 'Explore novels, poetry, authors, characters, and literary ideas.', 'book', '#A855F7')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color;

WITH question_bank(slug, question, correct_answer, wrong_answers, difficulty, explanation) AS (
  VALUES
  ('geography', 'Which country has the most time zones, including its overseas territories?', 'France', ARRAY['Russia', 'United States', 'China'], 3, 'France has many overseas territories, giving it more time zones than any other country.'),
  ('geography', 'What is the only country that is also a continent?', 'Australia', ARRAY['Greenland', 'Iceland', 'Madagascar'], 1, 'Australia is both a sovereign country and the main landmass of the Australian continent.'),
  ('geography', 'Which city sits on two continents, Europe and Asia?', 'Istanbul', ARRAY['Cairo', 'Moscow', 'Athens'], 2, 'Istanbul spans the Bosporus Strait, connecting Europe and Asia.'),
  ('geography', 'What is the driest non-polar desert in the world?', 'Atacama Desert', ARRAY['Sahara Desert', 'Gobi Desert', 'Kalahari Desert'], 2, 'The Atacama Desert in South America is famous for extreme dryness.'),
  ('geography', 'Which African country has the largest population?', 'Nigeria', ARRAY['Egypt', 'Ethiopia', 'South Africa'], 1, 'Nigeria is Africa''s most populous country.'),
  ('geography', 'What is the deepest known point in the ocean?', 'Challenger Deep', ARRAY['Puerto Rico Trench', 'Java Trench', 'Tonga Trench'], 3, 'Challenger Deep in the Mariana Trench is the deepest known ocean point.'),
  ('geography', 'Which river flows through Baghdad?', 'Tigris', ARRAY['Nile', 'Euphrates', 'Jordan'], 2, 'Baghdad is located on the Tigris River.'),
  ('geography', 'What is the capital of New Zealand?', 'Wellington', ARRAY['Auckland', 'Christchurch', 'Queenstown'], 1, 'Wellington is New Zealand''s capital city.'),
  ('geography', 'Which mountain range separates Europe and Asia?', 'Ural Mountains', ARRAY['Alps', 'Caucasus Mountains', 'Carpathians'], 2, 'The Ural Mountains are commonly used as part of the Europe-Asia boundary.'),
  ('geography', 'Which country is home to Lake Baikal?', 'Russia', ARRAY['Mongolia', 'Kazakhstan', 'China'], 2, 'Lake Baikal in Siberia is the world''s deepest freshwater lake.'),
  ('geography', 'What country does this flag belong to: a red circle on a white field?', 'Japan', ARRAY['South Korea', 'Bangladesh', 'Vietnam'], 1, 'Japan''s flag features a red sun disc on white.'),
  ('geography', 'Which country has Kathmandu as its capital?', 'Nepal', ARRAY['Bhutan', 'Sri Lanka', 'Myanmar'], 1, 'Kathmandu is the capital city of Nepal.'),
  ('geography', 'Which sea is the lowest exposed point on Earth''s land surface?', 'Dead Sea', ARRAY['Caspian Sea', 'Red Sea', 'Black Sea'], 2, 'The Dead Sea shore is the lowest exposed land elevation on Earth.'),
  ('geography', 'Which South American country is landlocked?', 'Bolivia', ARRAY['Peru', 'Chile', 'Ecuador'], 1, 'Bolivia is one of South America''s two landlocked countries.'),
  ('geography', 'What is the largest island in the world?', 'Greenland', ARRAY['New Guinea', 'Borneo', 'Madagascar'], 2, 'Greenland is the world''s largest island by area.'),
  ('geography', 'Which country is shaped like a boot?', 'Italy', ARRAY['Greece', 'Portugal', 'Croatia'], 1, 'Italy is famously boot-shaped on maps.'),
  ('geography', 'Which capital city is closest to the equator?', 'Quito', ARRAY['Nairobi', 'Singapore', 'Bogota'], 3, 'Quito, Ecuador, lies very close to the equator.'),
  ('geography', 'Which canal connects the Mediterranean Sea to the Red Sea?', 'Suez Canal', ARRAY['Panama Canal', 'Erie Canal', 'Kiel Canal'], 1, 'The Suez Canal links the Mediterranean and Red seas.'),
  ('geography', 'Which country has the city of Timbuktu?', 'Mali', ARRAY['Morocco', 'Niger', 'Sudan'], 2, 'Timbuktu is a historic city in Mali.'),
  ('geography', 'What is the smallest country in the world by area?', 'Vatican City', ARRAY['Monaco', 'San Marino', 'Liechtenstein'], 1, 'Vatican City is the world''s smallest sovereign state by area.'),

  ('science', 'What particle has a negative electric charge?', 'Electron', ARRAY['Proton', 'Neutron', 'Photon'], 1, 'Electrons carry negative charge.'),
  ('science', 'What force keeps planets in orbit around the Sun?', 'Gravity', ARRAY['Magnetism', 'Friction', 'Buoyancy'], 1, 'Gravity attracts planets toward the Sun while their motion carries them forward.'),
  ('science', 'Which gas makes up most of Earth''s atmosphere?', 'Nitrogen', ARRAY['Oxygen', 'Carbon dioxide', 'Hydrogen'], 1, 'Nitrogen makes up about 78 percent of Earth''s atmosphere.'),
  ('science', 'What is the pH of a neutral solution at room temperature?', '7', ARRAY['0', '3', '14'], 1, 'A neutral solution has a pH of 7.'),
  ('science', 'Which organelle is often called the powerhouse of the cell?', 'Mitochondrion', ARRAY['Ribosome', 'Nucleus', 'Chloroplast'], 1, 'Mitochondria produce much of a cell''s usable energy.'),
  ('science', 'What is the chemical symbol for gold?', 'Au', ARRAY['Ag', 'Gd', 'Go'], 1, 'Gold''s symbol is Au, from the Latin aurum.'),
  ('science', 'Which planet has the most prominent ring system?', 'Saturn', ARRAY['Mars', 'Venus', 'Mercury'], 1, 'Saturn is famous for its bright, extensive rings.'),
  ('science', 'What type of energy is stored in a stretched rubber band?', 'Elastic potential energy', ARRAY['Thermal energy', 'Chemical energy', 'Nuclear energy'], 2, 'Stretching stores elastic potential energy.'),
  ('science', 'Which scientist proposed the three laws of motion?', 'Isaac Newton', ARRAY['Albert Einstein', 'Marie Curie', 'Charles Darwin'], 1, 'Newton formulated the classical laws of motion.'),
  ('science', 'What is the process where plants make food using sunlight?', 'Photosynthesis', ARRAY['Respiration', 'Fermentation', 'Evaporation'], 1, 'Photosynthesis converts light energy into chemical energy in plants.'),
  ('science', 'What is the name for animals active mainly at night?', 'Nocturnal', ARRAY['Diurnal', 'Migratory', 'Aquatic'], 1, 'Nocturnal animals are active during the night.'),
  ('science', 'Which layer of Earth lies between crust and core?', 'Mantle', ARRAY['Lithosphere', 'Troposphere', 'Hydrosphere'], 2, 'The mantle sits between Earth''s crust and core.'),
  ('science', 'What is the SI unit of electric current?', 'Ampere', ARRAY['Volt', 'Ohm', 'Watt'], 2, 'Electric current is measured in amperes.'),
  ('science', 'What does DNA stand for?', 'Deoxyribonucleic acid', ARRAY['Dynamic nuclear acid', 'Double nitrogen atom', 'Digital nucleotide array'], 2, 'DNA stands for deoxyribonucleic acid.'),
  ('science', 'Which electromagnetic waves have the shortest wavelength?', 'Gamma rays', ARRAY['Radio waves', 'Microwaves', 'Infrared waves'], 3, 'Gamma rays have the shortest wavelengths and highest photon energies.'),
  ('science', 'What is the most abundant element in the universe?', 'Hydrogen', ARRAY['Helium', 'Oxygen', 'Carbon'], 1, 'Hydrogen is the most abundant element in the universe.'),
  ('science', 'What is the study of fungi called?', 'Mycology', ARRAY['Botany', 'Zoology', 'Geology'], 3, 'Mycology is the scientific study of fungi.'),
  ('science', 'What kind of bond shares electron pairs between atoms?', 'Covalent bond', ARRAY['Ionic bond', 'Metallic bond', 'Hydrogen bond'], 2, 'Covalent bonds form when atoms share electron pairs.'),
  ('science', 'Which moon is the largest in the solar system?', 'Ganymede', ARRAY['Titan', 'Europa', 'The Moon'], 3, 'Ganymede, a moon of Jupiter, is the largest moon in the solar system.'),
  ('science', 'What is absolute zero in Celsius?', '-273.15 C', ARRAY['0 C', '-100 C', '-459.67 C'], 3, 'Absolute zero equals -273.15 degrees Celsius.'),

  ('health', 'Which vitamin is produced in skin when exposed to sunlight?', 'Vitamin D', ARRAY['Vitamin A', 'Vitamin B12', 'Vitamin K'], 1, 'Sunlight helps the skin produce vitamin D.'),
  ('health', 'What mineral is important for strong bones and teeth?', 'Calcium', ARRAY['Iron', 'Sodium', 'Zinc'], 1, 'Calcium supports bone and tooth structure.'),
  ('health', 'Which part of blood helps it clot?', 'Platelets', ARRAY['Plasma', 'White blood cells', 'Red blood cells'], 1, 'Platelets help blood form clots.'),
  ('health', 'What is the body''s main breathing muscle?', 'Diaphragm', ARRAY['Biceps', 'Trapezius', 'Hamstring'], 2, 'The diaphragm contracts and relaxes to help move air in and out of the lungs.'),
  ('health', 'Which organ filters waste from the blood to make urine?', 'Kidney', ARRAY['Spleen', 'Pancreas', 'Gallbladder'], 1, 'Kidneys filter blood and produce urine.'),
  ('health', 'What is the largest part of the human brain?', 'Cerebrum', ARRAY['Cerebellum', 'Brainstem', 'Hypothalamus'], 2, 'The cerebrum is the largest part of the brain.'),
  ('health', 'Which nutrient is the body''s main quick energy source?', 'Carbohydrates', ARRAY['Vitamins', 'Minerals', 'Water'], 1, 'Carbohydrates are a major source of quick energy.'),
  ('health', 'What does CPR stand for?', 'Cardiopulmonary resuscitation', ARRAY['Cardiac pulse recovery', 'Chest pressure restart', 'Circulatory pressure response'], 2, 'CPR stands for cardiopulmonary resuscitation.'),
  ('health', 'Which system protects the body from infection?', 'Immune system', ARRAY['Digestive system', 'Skeletal system', 'Endocrine system'], 1, 'The immune system defends the body against pathogens.'),
  ('health', 'What is a normal human body temperature in Celsius often rounded to?', '37 C', ARRAY['32 C', '40 C', '44 C'], 1, 'Normal body temperature is commonly rounded to 37 degrees Celsius.'),
  ('health', 'Which disease is caused by a lack of vitamin C?', 'Scurvy', ARRAY['Rickets', 'Anemia', 'Goiter'], 2, 'Severe vitamin C deficiency can cause scurvy.'),
  ('health', 'What type of exercise mainly improves heart and lung endurance?', 'Aerobic exercise', ARRAY['Static stretching', 'Balance drills', 'Isometric holds'], 1, 'Aerobic exercise challenges the heart and lungs over time.'),
  ('health', 'Which organ produces insulin?', 'Pancreas', ARRAY['Liver', 'Kidney', 'Stomach'], 2, 'The pancreas produces insulin.'),
  ('health', 'What is the medical term for high blood pressure?', 'Hypertension', ARRAY['Hypoglycemia', 'Hypothermia', 'Hyperopia'], 2, 'Hypertension means high blood pressure.'),
  ('health', 'Which bone protects the brain?', 'Skull', ARRAY['Sternum', 'Pelvis', 'Femur'], 1, 'The skull protects the brain.'),
  ('health', 'What is the main function of red blood cells?', 'Carry oxygen', ARRAY['Fight infection', 'Digest fat', 'Produce hormones'], 1, 'Red blood cells transport oxygen using hemoglobin.'),
  ('health', 'Which sleep stage is strongly associated with vivid dreaming?', 'REM sleep', ARRAY['Light sleep', 'Deep sleep', 'Wakefulness'], 2, 'Vivid dreaming is commonly linked with REM sleep.'),
  ('health', 'What is the hardest substance in the human body?', 'Tooth enamel', ARRAY['Bone', 'Cartilage', 'Keratin'], 2, 'Tooth enamel is the hardest substance in the body.'),
  ('health', 'Which joint type is the shoulder?', 'Ball-and-socket joint', ARRAY['Hinge joint', 'Pivot joint', 'Fixed joint'], 2, 'The shoulder is a ball-and-socket joint.'),
  ('health', 'What does BMI stand for?', 'Body mass index', ARRAY['Basic muscle intake', 'Blood metabolism indicator', 'Body mineral index'], 1, 'BMI stands for body mass index.'),

  ('history', 'Which civilization developed cuneiform writing?', 'Sumerians', ARRAY['Romans', 'Maya', 'Vikings'], 3, 'The Sumerians developed cuneiform in ancient Mesopotamia.'),
  ('history', 'Who was the first emperor of China?', 'Qin Shi Huang', ARRAY['Kublai Khan', 'Sun Yat-sen', 'Emperor Gaozu'], 3, 'Qin Shi Huang unified China and became its first emperor.'),
  ('history', 'Which event began in 1789 in France?', 'French Revolution', ARRAY['Industrial Revolution', 'Russian Revolution', 'Glorious Revolution'], 1, 'The French Revolution began in 1789.'),
  ('history', 'Which ship carried the Pilgrims to New England in 1620?', 'Mayflower', ARRAY['Santa Maria', 'Endeavour', 'Beagle'], 1, 'The Mayflower carried the Pilgrims to New England.'),
  ('history', 'Who was known as the Maid of Orleans?', 'Joan of Arc', ARRAY['Cleopatra', 'Boudica', 'Catherine de Medici'], 2, 'Joan of Arc is known as the Maid of Orleans.'),
  ('history', 'Which empire was ruled from Constantinople after the Western Roman Empire fell?', 'Byzantine Empire', ARRAY['Ottoman Empire', 'Mongol Empire', 'Persian Empire'], 2, 'The Byzantine Empire continued Roman traditions from Constantinople.'),
  ('history', 'What wall divided a European capital during the Cold War?', 'Berlin Wall', ARRAY['Hadrian''s Wall', 'Great Wall', 'Western Wall'], 1, 'The Berlin Wall divided East and West Berlin.'),
  ('history', 'Which leader is associated with the Salt March in India?', 'Mahatma Gandhi', ARRAY['Jawaharlal Nehru', 'Subhas Chandra Bose', 'B. R. Ambedkar'], 2, 'Gandhi led the Salt March as a nonviolent protest against British salt laws.'),
  ('history', 'What ancient library was located in Egypt?', 'Library of Alexandria', ARRAY['Library of Pergamum', 'House of Wisdom', 'Vatican Library'], 2, 'The Library of Alexandria was one of the ancient world''s great knowledge centers.'),
  ('history', 'Which war was fought between the North and South in the United States?', 'American Civil War', ARRAY['War of 1812', 'Mexican-American War', 'Revolutionary War'], 1, 'The American Civil War was fought between Union and Confederate states.'),
  ('history', 'Who painted the ceiling of the Sistine Chapel?', 'Michelangelo', ARRAY['Leonardo da Vinci', 'Raphael', 'Donatello'], 1, 'Michelangelo painted the Sistine Chapel ceiling.'),
  ('history', 'Which city was buried by Mount Vesuvius in 79 CE?', 'Pompeii', ARRAY['Athens', 'Carthage', 'Sparta'], 1, 'Pompeii was buried by the eruption of Mount Vesuvius.'),
  ('history', 'Which dynasty built much of the Great Wall as seen today?', 'Ming dynasty', ARRAY['Han dynasty', 'Qing dynasty', 'Tang dynasty'], 3, 'Much of the visible Great Wall was built or rebuilt during the Ming dynasty.'),
  ('history', 'What year did humans first land on the Moon?', '1969', ARRAY['1959', '1972', '1981'], 1, 'Apollo 11 landed humans on the Moon in 1969.'),
  ('history', 'Who was the first woman to win a Nobel Prize?', 'Marie Curie', ARRAY['Rosalind Franklin', 'Ada Lovelace', 'Jane Addams'], 2, 'Marie Curie was the first woman to receive a Nobel Prize.'),
  ('history', 'Which trade route connected China with the Mediterranean world?', 'Silk Road', ARRAY['Amber Road', 'Spice Route', 'Trans-Saharan Route'], 1, 'The Silk Road connected East Asia with Central Asia, the Middle East, and Europe.'),
  ('history', 'Which empire was founded by Genghis Khan?', 'Mongol Empire', ARRAY['Ottoman Empire', 'Mughal Empire', 'Aztec Empire'], 1, 'Genghis Khan founded the Mongol Empire.'),
  ('history', 'Which document limited the power of the English king in 1215?', 'Magna Carta', ARRAY['Bill of Rights', 'Domesday Book', 'Treaty of Paris'], 2, 'Magna Carta limited royal authority and influenced constitutional law.'),
  ('history', 'What was the first successful vaccine developed for?', 'Smallpox', ARRAY['Polio', 'Measles', 'Rabies'], 2, 'Edward Jenner developed an early successful smallpox vaccine.'),
  ('history', 'Which city hosted the first modern Olympic Games in 1896?', 'Athens', ARRAY['Paris', 'Rome', 'London'], 1, 'The first modern Olympic Games were held in Athens in 1896.'),

  ('music', 'What is the term for the speed of a piece of music?', 'Tempo', ARRAY['Timbre', 'Harmony', 'Pitch'], 1, 'Tempo describes how fast or slow music is played.'),
  ('music', 'Which composer became deaf later in life and wrote the Ninth Symphony?', 'Ludwig van Beethoven', ARRAY['Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Franz Schubert'], 1, 'Beethoven composed major works even after losing much of his hearing.'),
  ('music', 'What family of instruments does the saxophone belong to?', 'Woodwind', ARRAY['Brass', 'Percussion', 'String'], 2, 'The saxophone is classified as a woodwind because it uses a reed.'),
  ('music', 'Which note is one semitone above C?', 'C sharp', ARRAY['B flat', 'D', 'E flat'], 1, 'C sharp is one semitone above C.'),
  ('music', 'What does forte mean in music?', 'Loud', ARRAY['Soft', 'Slow', 'Detached'], 1, 'Forte means loud.'),
  ('music', 'Which band released the album Abbey Road?', 'The Beatles', ARRAY['The Rolling Stones', 'The Who', 'Queen'], 1, 'Abbey Road is a Beatles album.'),
  ('music', 'What is the lowest standard female vocal range?', 'Contralto', ARRAY['Soprano', 'Mezzo-soprano', 'Tenor'], 2, 'Contralto is the lowest standard female vocal range.'),
  ('music', 'Which instrument is known for a double reed?', 'Oboe', ARRAY['Flute', 'Trumpet', 'Guitar'], 2, 'The oboe uses a double reed.'),
  ('music', 'What genre is strongly associated with improvisation and swing?', 'Jazz', ARRAY['Baroque', 'Punk', 'Disco'], 1, 'Jazz is strongly linked to improvisation and swing feel.'),
  ('music', 'Who composed The Four Seasons?', 'Antonio Vivaldi', ARRAY['Claude Debussy', 'Gustav Mahler', 'George Gershwin'], 2, 'Vivaldi composed The Four Seasons.'),
  ('music', 'How many beats are in a measure of common time?', '4', ARRAY['2', '3', '5'], 1, 'Common time is 4/4, with four beats per measure.'),
  ('music', 'Which singer is often called the Queen of Soul?', 'Aretha Franklin', ARRAY['Whitney Houston', 'Diana Ross', 'Tina Turner'], 1, 'Aretha Franklin is widely known as the Queen of Soul.'),
  ('music', 'What is a chord?', 'Three or more notes played together', ARRAY['A single beat', 'A tempo marking', 'A drum pattern'], 1, 'A chord is typically three or more notes sounded together.'),
  ('music', 'Which music format replaced many cassette sales in the 1990s?', 'Compact disc', ARRAY['Vinyl cylinder', '8-track tape', 'MiniDisc only'], 1, 'Compact discs became dominant for music sales in the 1990s.'),
  ('music', 'What is the name of a song''s repeated main section?', 'Chorus', ARRAY['Coda', 'Bridge', 'Intro'], 1, 'The chorus is the repeated central section of many songs.'),
  ('music', 'Which composer wrote the opera The Magic Flute?', 'Mozart', ARRAY['Wagner', 'Verdi', 'Puccini'], 2, 'Mozart wrote The Magic Flute.'),
  ('music', 'What instrument is Yo-Yo Ma famous for playing?', 'Cello', ARRAY['Violin', 'Piano', 'Clarinet'], 1, 'Yo-Yo Ma is a world-famous cellist.'),
  ('music', 'Which genre began in Jamaica and features offbeat rhythms?', 'Reggae', ARRAY['Flamenco', 'Bluegrass', 'Grunge'], 2, 'Reggae originated in Jamaica and often emphasizes offbeat rhythms.'),
  ('music', 'What is timbre?', 'The tone color of a sound', ARRAY['The speed of music', 'The loudness level', 'The written lyrics'], 3, 'Timbre is the quality or color that makes sounds distinct.'),
  ('music', 'Which symbol raises a note by one semitone?', 'Sharp', ARRAY['Flat', 'Rest', 'Clef'], 1, 'A sharp raises a pitch by one semitone.'),

  ('coding', 'What does HTML primarily describe?', 'Page structure', ARRAY['Database queries', 'Server memory', 'Image compression'], 1, 'HTML describes the structure and content of web pages.'),
  ('coding', 'Which CSS property changes text color?', 'color', ARRAY['font-style', 'background-size', 'display'], 1, 'The CSS color property controls text color.'),
  ('coding', 'What does API stand for?', 'Application Programming Interface', ARRAY['Automated Program Instruction', 'Applied Protocol Internet', 'Application Process Index'], 1, 'API stands for Application Programming Interface.'),
  ('coding', 'Which data structure uses first-in, first-out behavior?', 'Queue', ARRAY['Stack', 'Tree', 'Graph'], 2, 'A queue removes items in the same order they were added.'),
  ('coding', 'Which data structure uses last-in, first-out behavior?', 'Stack', ARRAY['Queue', 'Heap', 'Map'], 2, 'A stack removes the most recently added item first.'),
  ('coding', 'What is a boolean value?', 'True or false', ARRAY['A decimal number', 'A text paragraph', 'A file path'], 1, 'Boolean values represent true or false.'),
  ('coding', 'What does JSON stand for?', 'JavaScript Object Notation', ARRAY['Java Source Object Name', 'Joined Syntax Object Network', 'JavaScript Ordered Nodes'], 1, 'JSON stands for JavaScript Object Notation.'),
  ('coding', 'Which Git command records staged changes as a snapshot?', 'git commit', ARRAY['git clone', 'git fetch', 'git status'], 1, 'git commit creates a new commit from staged changes.'),
  ('coding', 'What is a function parameter?', 'An input variable for a function', ARRAY['A saved password', 'A compiler error', 'A CSS selector'], 1, 'Parameters let functions receive input values.'),
  ('coding', 'Which HTTP method is commonly used to create a resource?', 'POST', ARRAY['GET', 'TRACE', 'OPTIONS'], 1, 'POST is commonly used to create resources or submit data.'),
  ('coding', 'What does SQL mainly help you do?', 'Query relational databases', ARRAY['Style web pages', 'Compress videos', 'Draw vector icons'], 1, 'SQL is used to query and manage relational databases.'),
  ('coding', 'Which Big O notation describes binary search?', 'O(log n)', ARRAY['O(n)', 'O(n squared)', 'O(1) always'], 2, 'Binary search halves the search space each step, giving O(log n) time.'),
  ('coding', 'What is recursion?', 'A function calling itself', ARRAY['A variable changing type', 'A database backup', 'A network timeout'], 2, 'Recursion happens when a function calls itself.'),
  ('coding', 'Which JavaScript keyword declares a block-scoped variable?', 'let', ARRAY['var', 'def', 'dim'], 1, 'let declares block-scoped variables in JavaScript.'),
  ('coding', 'What is a race condition?', 'A timing bug from uncontrolled concurrent operations', ARRAY['A syntax typo', 'A fast animation', 'A failed login'], 3, 'Race conditions happen when timing affects shared state unexpectedly.'),
  ('coding', 'Which test checks small units of code in isolation?', 'Unit test', ARRAY['Load test', 'Usability test', 'Smoke alarm test'], 1, 'Unit tests focus on small pieces of code.'),
  ('coding', 'What does CRUD stand for?', 'Create, Read, Update, Delete', ARRAY['Copy, Run, Undo, Deploy', 'Cache, Route, Upload, Download', 'Compile, Render, Use, Debug'], 1, 'CRUD names the four basic data operations.'),
  ('coding', 'Which symbol usually starts an ID selector in CSS?', '#', ARRAY['.', '*', '@'], 1, 'CSS ID selectors start with #.'),
  ('coding', 'What is a closure?', 'A function bundled with its surrounding scope', ARRAY['A closed browser tab', 'A finished database row', 'A private Git branch'], 3, 'Closures let functions remember variables from their surrounding scope.'),
  ('coding', 'Which command usually installs Node project dependencies from package.json?', 'npm install', ARRAY['node start', 'git init', 'css build'], 1, 'npm install reads package metadata and installs dependencies.'),

  ('technology', 'What does CPU stand for?', 'Central Processing Unit', ARRAY['Computer Power Utility', 'Core Program Unit', 'Central Pixel Unit'], 1, 'CPU stands for Central Processing Unit.'),
  ('technology', 'What does RAM store while a computer is running?', 'Temporary working data', ARRAY['Permanent archives only', 'Printed documents', 'Screen brightness'], 1, 'RAM stores temporary data programs need while running.'),
  ('technology', 'Which protocol secures web traffic with encryption?', 'HTTPS', ARRAY['HTTP', 'FTP', 'SMTP'], 1, 'HTTPS encrypts web traffic using TLS.'),
  ('technology', 'What does SSD stand for?', 'Solid-state drive', ARRAY['System storage dock', 'Secure software device', 'Signal sound driver'], 1, 'SSD stands for solid-state drive.'),
  ('technology', 'Which company created the Android operating system originally?', 'Android Inc.', ARRAY['Apple', 'Nokia', 'IBM'], 3, 'Android began at Android Inc. before Google acquired it.'),
  ('technology', 'What is phishing?', 'Tricking people into revealing sensitive information', ARRAY['Speeding up a processor', 'Repairing a display', 'Compressing a file'], 1, 'Phishing uses deception to steal credentials or sensitive data.'),
  ('technology', 'What does GPU stand for?', 'Graphics Processing Unit', ARRAY['General Power Utility', 'Global Program Unit', 'Graph Protocol User'], 1, 'GPU stands for Graphics Processing Unit.'),
  ('technology', 'Which storage service keeps files on remote servers accessed by internet?', 'Cloud storage', ARRAY['Optical zoom', 'Local clipboard', 'Analog radio'], 1, 'Cloud storage keeps data on internet-accessible remote servers.'),
  ('technology', 'What does two-factor authentication add?', 'A second proof of identity', ARRAY['A larger monitor', 'A second browser', 'A faster charger'], 1, 'Two-factor authentication requires another identity proof beyond a password.'),
  ('technology', 'Which wireless technology is commonly used for short-range earbuds?', 'Bluetooth', ARRAY['Ethernet', 'HDMI', 'SATA'], 1, 'Bluetooth is common for short-range wireless audio.'),
  ('technology', 'What is machine learning?', 'Systems learning patterns from data', ARRAY['Manual keyboard repair', 'Cable manufacturing', 'Screen calibration only'], 2, 'Machine learning trains systems to find patterns in data.'),
  ('technology', 'What does URL stand for?', 'Uniform Resource Locator', ARRAY['Universal Routing Link', 'User Request Label', 'Unified Resource Login'], 1, 'URL stands for Uniform Resource Locator.'),
  ('technology', 'Which device converts digital signals for network routing at home?', 'Router', ARRAY['Projector', 'Scanner', 'Stylus'], 1, 'Routers direct network traffic between devices and networks.'),
  ('technology', 'What is open-source software?', 'Software with source code available to inspect and modify', ARRAY['Software with no users', 'Software only for one laptop', 'Software without updates'], 1, 'Open-source software makes source code available under a license.'),
  ('technology', 'Which port shape is reversible and common on modern phones and laptops?', 'USB-C', ARRAY['VGA', 'PS/2', 'Parallel port'], 1, 'USB-C is reversible and common on modern devices.'),
  ('technology', 'What does IoT stand for?', 'Internet of Things', ARRAY['Input output transfer', 'Index of tools', 'Internet only terminal'], 2, 'IoT stands for Internet of Things.'),
  ('technology', 'What is a firewall used for?', 'Filtering network traffic', ARRAY['Increasing screen pixels', 'Cooling the CPU', 'Charging batteries'], 1, 'Firewalls filter network traffic based on rules.'),
  ('technology', 'Which unit measures data transfer rate?', 'Bits per second', ARRAY['Degrees Celsius', 'Lumens', 'Newtons'], 1, 'Data transfer rate is commonly measured in bits per second.'),
  ('technology', 'What is an IP address?', 'A network address for a device', ARRAY['A type of battery', 'A screen resolution', 'A printer cartridge'], 1, 'An IP address identifies a device on a network.'),
  ('technology', 'What does CAPTCHA try to distinguish?', 'Humans from automated bots', ARRAY['Phones from laptops', 'Images from videos', 'Speakers from microphones'], 2, 'CAPTCHAs are designed to tell humans and bots apart.'),

  ('sports', 'How many players are on the field for one soccer team during normal play?', '11', ARRAY['7', '9', '15'], 1, 'A soccer team fields 11 players during normal play.'),
  ('sports', 'Which sport uses a shuttlecock?', 'Badminton', ARRAY['Squash', 'Table tennis', 'Volleyball'], 1, 'Badminton is played with a shuttlecock.'),
  ('sports', 'What is a hat-trick in soccer?', 'Three goals by one player in a match', ARRAY['Three yellow cards', 'Three goalkeepers', 'Three corner kicks'], 1, 'A soccer hat-trick is three goals by one player in a match.'),
  ('sports', 'Which country hosted the 2016 Summer Olympics?', 'Brazil', ARRAY['China', 'Japan', 'United Kingdom'], 1, 'Rio de Janeiro, Brazil, hosted the 2016 Summer Olympics.'),
  ('sports', 'In tennis, what score comes after deuce when a player wins the next point?', 'Advantage', ARRAY['Love', 'Set', 'Break'], 1, 'After deuce, the next point gives a player advantage.'),
  ('sports', 'How many rings are on the Olympic flag?', '5', ARRAY['4', '6', '7'], 1, 'The Olympic flag has five interlocking rings.'),
  ('sports', 'Which sport is associated with the term slam dunk?', 'Basketball', ARRAY['Cricket', 'Golf', 'Rugby'], 1, 'A slam dunk is a basketball shot.'),
  ('sports', 'What is the maximum break in standard snooker?', '147', ARRAY['100', '180', '300'], 3, 'A maximum snooker break is 147 points.'),
  ('sports', 'Which country is famous for sumo wrestling?', 'Japan', ARRAY['Thailand', 'India', 'Mongolia'], 1, 'Sumo wrestling is strongly associated with Japan.'),
  ('sports', 'In cricket, how many runs is a boundary hit over the rope without bouncing?', '6', ARRAY['3', '4', '8'], 1, 'A ball hit over the boundary without bouncing scores six runs.'),
  ('sports', 'Which sport has positions called pitcher and catcher?', 'Baseball', ARRAY['Hockey', 'Basketball', 'Rugby'], 1, 'Pitcher and catcher are baseball positions.'),
  ('sports', 'What color jersey does the Tour de France leader wear?', 'Yellow', ARRAY['Green', 'Red', 'Blue'], 2, 'The Tour de France overall leader wears the yellow jersey.'),
  ('sports', 'Which martial art means gentle way in Japanese?', 'Judo', ARRAY['Karate', 'Taekwondo', 'Kendo'], 2, 'Judo is often translated as the gentle way.'),
  ('sports', 'How long is a marathon?', '42.195 km', ARRAY['21.1 km', '50 km', '10 km'], 2, 'A marathon is 42.195 kilometers.'),
  ('sports', 'Which sport is played at Wimbledon?', 'Tennis', ARRAY['Golf', 'Cricket', 'Polo'], 1, 'Wimbledon is one of tennis''s major tournaments.'),
  ('sports', 'What is the only sport played on the Moon?', 'Golf', ARRAY['Soccer', 'Baseball', 'Tennis'], 3, 'Astronaut Alan Shepard hit golf balls on the Moon during Apollo 14.'),
  ('sports', 'In volleyball, how many contacts does a team usually get before sending the ball over?', '3', ARRAY['1', '2', '5'], 1, 'Teams usually get up to three contacts.'),
  ('sports', 'Which chess piece moves in an L shape?', 'Knight', ARRAY['Bishop', 'Rook', 'Queen'], 1, 'The knight moves in an L shape.'),
  ('sports', 'Which sport uses the terms birdie and eagle?', 'Golf', ARRAY['Boxing', 'Swimming', 'Fencing'], 1, 'Birdie and eagle are golf scoring terms.'),
  ('sports', 'What does VAR stand for in soccer?', 'Video Assistant Referee', ARRAY['Verified Attack Rule', 'Virtual Arena Replay', 'Visual Advantage Review'], 2, 'VAR stands for Video Assistant Referee.'),

  ('movies', 'Who directed Jurassic Park?', 'Steven Spielberg', ARRAY['James Cameron', 'George Lucas', 'Ridley Scott'], 1, 'Steven Spielberg directed Jurassic Park.'),
  ('movies', 'Which movie features the line May the Force be with you?', 'Star Wars', ARRAY['Star Trek', 'The Matrix', 'Avatar'], 1, 'May the Force be with you is from Star Wars.'),
  ('movies', 'What is the highest-grossing film of 1997 centered on a ship disaster?', 'Titanic', ARRAY['The Perfect Storm', 'Pearl Harbor', 'Poseidon'], 1, 'Titanic was released in 1997 and became a massive box office success.'),
  ('movies', 'Which animation studio made Toy Story?', 'Pixar', ARRAY['DreamWorks', 'Studio Ghibli', 'Laika'], 1, 'Toy Story was Pixar''s first feature film.'),
  ('movies', 'Who played the Joker in The Dark Knight?', 'Heath Ledger', ARRAY['Joaquin Phoenix', 'Jack Nicholson', 'Jared Leto'], 1, 'Heath Ledger played the Joker in The Dark Knight.'),
  ('movies', 'Which film won Best Picture at the first Academy Awards?', 'Wings', ARRAY['Sunrise', 'Metropolis', 'The Jazz Singer'], 3, 'Wings won Outstanding Picture at the first Academy Awards.'),
  ('movies', 'What is the fictional African nation in Black Panther?', 'Wakanda', ARRAY['Genovia', 'Latveria', 'Zamunda'], 1, 'Black Panther is set largely in Wakanda.'),
  ('movies', 'Which director is known for Spirited Away?', 'Hayao Miyazaki', ARRAY['Akira Kurosawa', 'Satoshi Kon', 'Isao Takahata'], 2, 'Hayao Miyazaki directed Spirited Away.'),
  ('movies', 'In The Matrix, which pill does Neo take?', 'Red pill', ARRAY['Blue pill', 'Green pill', 'White pill'], 1, 'Neo takes the red pill.'),
  ('movies', 'Which movie monster first appeared in a 1954 Japanese film?', 'Godzilla', ARRAY['King Kong', 'Mothra', 'Gamera'], 2, 'Godzilla first appeared in the 1954 Japanese film Godzilla.'),
  ('movies', 'Who composed many famous scores for Star Wars and Indiana Jones?', 'John Williams', ARRAY['Hans Zimmer', 'Ennio Morricone', 'Howard Shore'], 1, 'John Williams composed iconic scores for both franchises.'),
  ('movies', 'Which film features a young lion named Simba?', 'The Lion King', ARRAY['Madagascar', 'Finding Nemo', 'Bambi'], 1, 'Simba is the main lion character in The Lion King.'),
  ('movies', 'What genre is film noir most associated with?', 'Crime drama', ARRAY['Musical comedy', 'Nature documentary', 'Fantasy romance'], 2, 'Film noir is strongly associated with stylized crime dramas.'),
  ('movies', 'Which actor played Iron Man in the Marvel Cinematic Universe?', 'Robert Downey Jr.', ARRAY['Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth'], 1, 'Robert Downey Jr. played Tony Stark and Iron Man.'),
  ('movies', 'Which movie uses the subtitle The Fellowship of the Ring?', 'The Lord of the Rings', ARRAY['Harry Potter', 'Narnia', 'The Hobbit'], 1, 'The Fellowship of the Ring is the first Lord of the Rings film.'),
  ('movies', 'What does CGI stand for?', 'Computer-generated imagery', ARRAY['Cinema graphic index', 'Camera guide interface', 'Color graded image'], 1, 'CGI stands for computer-generated imagery.'),
  ('movies', 'Which famous shark movie was released in 1975?', 'Jaws', ARRAY['Deep Blue Sea', 'The Meg', 'Open Water'], 1, 'Jaws was released in 1975.'),
  ('movies', 'Who directed Pulp Fiction?', 'Quentin Tarantino', ARRAY['Martin Scorsese', 'Francis Ford Coppola', 'David Fincher'], 2, 'Quentin Tarantino directed Pulp Fiction.'),
  ('movies', 'Which film popularized the quote I''ll be back?', 'The Terminator', ARRAY['RoboCop', 'Predator', 'Die Hard'], 1, 'The Terminator popularized the line I''ll be back.'),
  ('movies', 'What is the name of the cowboy doll in Toy Story?', 'Woody', ARRAY['Buzz', 'Andy', 'Jessie'], 1, 'Woody is the cowboy doll in Toy Story.'),

  ('literature', 'Who wrote Pride and Prejudice?', 'Jane Austen', ARRAY['Charlotte Bronte', 'Mary Shelley', 'George Eliot'], 1, 'Jane Austen wrote Pride and Prejudice.'),
  ('literature', 'Which novel begins with Call me Ishmael?', 'Moby-Dick', ARRAY['The Old Man and the Sea', 'Treasure Island', 'Dracula'], 2, 'Moby-Dick opens with Call me Ishmael.'),
  ('literature', 'Who wrote the play Hamlet?', 'William Shakespeare', ARRAY['Christopher Marlowe', 'Oscar Wilde', 'Arthur Miller'], 1, 'Shakespeare wrote Hamlet.'),
  ('literature', 'What is the name of the hobbit who carries the One Ring to Mordor?', 'Frodo Baggins', ARRAY['Bilbo Baggins', 'Samwise Gamgee', 'Pippin Took'], 1, 'Frodo carries the One Ring toward Mordor.'),
  ('literature', 'Which author created Sherlock Holmes?', 'Arthur Conan Doyle', ARRAY['Agatha Christie', 'Edgar Allan Poe', 'G. K. Chesterton'], 1, 'Arthur Conan Doyle created Sherlock Holmes.'),
  ('literature', 'What is a haiku traditionally known for?', 'A 5-7-5 syllable pattern', ARRAY['Fourteen lines', 'Rhyming couplets only', 'A five-act structure'], 2, 'Traditional English-language haiku are often taught with a 5-7-5 syllable pattern.'),
  ('literature', 'Who wrote Frankenstein?', 'Mary Shelley', ARRAY['Bram Stoker', 'Emily Dickinson', 'Virginia Woolf'], 1, 'Mary Shelley wrote Frankenstein.'),
  ('literature', 'Which dystopian novel features Big Brother?', 'Nineteen Eighty-Four', ARRAY['Brave New World', 'Fahrenheit 451', 'The Handmaid''s Tale'], 1, 'Big Brother is a symbol of surveillance in Nineteen Eighty-Four.'),
  ('literature', 'Who wrote Things Fall Apart?', 'Chinua Achebe', ARRAY['Wole Soyinka', 'Ngugi wa Thiong''o', 'Chimamanda Ngozi Adichie'], 2, 'Chinua Achebe wrote Things Fall Apart.'),
  ('literature', 'What is the term for a comparison using like or as?', 'Simile', ARRAY['Metaphor', 'Alliteration', 'Hyperbole'], 1, 'A simile compares using like or as.'),
  ('literature', 'Which Greek poet is credited with the Iliad and the Odyssey?', 'Homer', ARRAY['Virgil', 'Sophocles', 'Ovid'], 1, 'Homer is traditionally credited with the Iliad and Odyssey.'),
  ('literature', 'Who wrote The Raven?', 'Edgar Allan Poe', ARRAY['Walt Whitman', 'Robert Frost', 'T. S. Eliot'], 1, 'Edgar Allan Poe wrote The Raven.'),
  ('literature', 'Which novel features the character Atticus Finch?', 'To Kill a Mockingbird', ARRAY['The Great Gatsby', 'Of Mice and Men', 'Catch-22'], 1, 'Atticus Finch appears in To Kill a Mockingbird.'),
  ('literature', 'What is an unreliable narrator?', 'A narrator whose account cannot be fully trusted', ARRAY['A narrator with no name', 'A narrator outside the story', 'A narrator who never speaks'], 3, 'An unreliable narrator gives a version of events readers should question.'),
  ('literature', 'Who wrote One Hundred Years of Solitude?', 'Gabriel Garcia Marquez', ARRAY['Jorge Luis Borges', 'Mario Vargas Llosa', 'Pablo Neruda'], 2, 'Gabriel Garcia Marquez wrote One Hundred Years of Solitude.'),
  ('literature', 'Which book series features Hogwarts?', 'Harry Potter', ARRAY['Percy Jackson', 'His Dark Materials', 'A Series of Unfortunate Events'], 1, 'Hogwarts is the wizarding school in Harry Potter.'),
  ('literature', 'What is alliteration?', 'Repetition of initial consonant sounds', ARRAY['A surprise ending', 'A borrowed quote', 'A plot summary'], 2, 'Alliteration repeats initial consonant sounds.'),
  ('literature', 'Who wrote The Handmaid''s Tale?', 'Margaret Atwood', ARRAY['Ursula K. Le Guin', 'Toni Morrison', 'Doris Lessing'], 2, 'Margaret Atwood wrote The Handmaid''s Tale.'),
  ('literature', 'Which novel features Jay Gatsby?', 'The Great Gatsby', ARRAY['Great Expectations', 'The Sun Also Rises', 'Invisible Man'], 1, 'Jay Gatsby is the central figure of The Great Gatsby.'),
  ('literature', 'What is the climax of a story?', 'The point of greatest tension or turning point', ARRAY['The list of characters', 'The first sentence', 'The publication date'], 1, 'The climax is the story''s major turning point or peak tension.')
)
INSERT INTO public.questions (category_id, question, correct_answer, wrong_answers, difficulty, explanation)
SELECT
  c.id,
  qb.question,
  qb.correct_answer,
  qb.wrong_answers,
  qb.difficulty,
  qb.explanation
FROM public.categories c
JOIN question_bank qb ON qb.slug = c.slug
WHERE NOT EXISTS (
  SELECT 1
  FROM public.questions existing
  WHERE existing.category_id = c.id
    AND existing.question = qb.question
    AND existing.correct_answer = qb.correct_answer
);
